k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: 2e68ce7b-7ffe-531a-b866-2949581f5b91
    cluster_name: Ira's cluster
- manifest_path: /manifests
  cluster_info:
    cluster_id: 2e68ce7b-7ffe-531a-b866-2949581f5b91
    cluster_name: Ira's cluster
